apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app:  my-application-blue
    version: my-application-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  